app = 'insidethe-ai-backend-launchpad'
primary_region = 'lax'

[build]

[env]
  ENV = 'launchpad'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
